repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: f71fa2 #v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: detect-private-key

  - repo: https://github.com/antonbabenko/pre-comit-terraform
    rev: 7fb9561 #v1.77.1
    hooks:
      - id: terraform_fmt

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: tflint
      #- id: terraform-validate
      #- id: terraform-fmt

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.71.0
    hooks:
      #- id: terraform_tfsec
      - id: terraform_docs
      - id: terraform_checkov

  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.17
    hooks:
      - id: markdown-link-check