formatter: markdown
header-from: main.tf
output-file: README.md
output-mode: inject

sections:
  - header
  - providers
  - inputs
  - outputs
  - resources
  - footer

sort:
  enabled: true
  by: name

settings:
  indent: 2
  escape: false
  required: true
